enum class Categories {
    GAME_CASINO, GAME_SIMULATION, GAME_CARD, GAME_CASUAL, GAME_SPORTS, GAME_MUSIC, GAME_BOARD, GAME_TRIVIA, GAME_PUZZLE, GAME_ADVENTURE, GAME_STRATEGY,
    GAME_ARCADE, GAME_RACING, GAME_ACTION, GAME_ROLE_PLAYING, GAME_EDUCATIONAL, GAME_WORD, BOOKS_AND_REFERENCE, COMICS, NEWS_AND_MAGAZINES, EVENTS,
    LIBRARIES_AND_DEMO, SOCIAL, DATING, COMMUNICATION, TRAVEL_AND_LOCAL, MAPS_AND_NAVIGATION, SHOPPING, FOOD_AND_DRINK, ENTERTAINMENT, LIFESTYLE,
    BEAUTY, HEALTH_AND_FITNESS,  AUTO_AND_VEHICLES, SPORTS, BUSINESS, PARENTING, WEATHER, MUSIC_AND_AUDIO, PERSONALIZATION, HOUSE_AND_HOME, PHOTOGRAPHY,
    VIDEO_PLAYERS, PRODUCTIVITY, TOOLS, EDUCATION, FINANCE, MEDICAL, ART_AND_DESIGN, GAMES, BOOKS_AND_NEWS, TRAVEL,  OTHER
}